name: tests

on: [push, pull_request]

jobs:

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install virtualenv from poetry
        uses: 20c/workflows/poetry@v1
      - name: Run linters
        run: |
            poetry run pre-commit run --all-files
  test:
    needs: linting
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install virtualenv from poetry
        uses: 20c/workflows/poetry@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: |
          poetry run tox
          poetry run coverage report
      # upload coverage stats
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true