site_name: pybird
site_url: https://github.com/20c/pybird

theme: readthedocs

nav:
  - Home: index.md
  - Examples: examples.md
  - Field Lists: field-lists.md
  - Testing: testing.md

markdown_extensions:
  - markdown_include.include
  - admonition
  - pymdgen